In [2]:
import pandas as pd

In [3]:
# Q1. version of Pandas installed

pd.__version__

'3.0.6'

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [7]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [13]:
# Q2. How many records are in the dataset?

number_of_records = len(df)

In [15]:
len(df)

10000

In [20]:
# Q3. How many fuel types are presented in the dataset?

df.fuel_type.nunique()

3

In [21]:
# Q4. How many columns in the dataset have missing values?

df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [23]:
# Q5. What's the maximum fuel efficiency of cars from Asia?

df.fuel_efficiency_mpg.max()

np.float64(41.2)

In [24]:
# Q6. Median value of horsepower
# 1. Find the median value of the horsepower column in the dataset.

df.horsepower.median()

np.float64(254.0)

In [25]:
# 2. Next, calculate the most frequent value of the same horsepower column.

df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [62]:
# 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
 
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

In [29]:
df['horsepower']

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [63]:
# 4. Now, calculate the median value of horsepower once again.

df.horsepower.median()

np.float64(252.0)

In [38]:
# Q7. Sum of weights
# 1. Select all the cars from Asia

df[
   df['origin']=='Asia'
  ]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [39]:
# 2. Select only columns vehicle_weight and model_year

df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [45]:
# 3. Select the first 7 values

df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [46]:
# 4. Get the underlying NumPy array. Let's call it X.

X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values

In [47]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [48]:
#5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

import numpy as np

In [49]:
XTX = np.dot(X.T, X)

In [50]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [51]:
# 6. Invert XTX.

XTX_invert = np.linalg.inv(XTX)

In [52]:
XTX_invert

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [53]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [54]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [56]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = np.dot(np.dot(XTX_invert, X.T), y)

In [57]:
w

array([0.13644777, 0.2327492 ])

In [ ]:
# 9. What's the sum of all the elements of the result?

total_sum = w.sum().round(3)

In [67]:
total_sum

np.float64(0.369)